import type { Metadata } from "next"
import Link from "next/link"
import { BarChart3, TrendingUp, Presentation, ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { CTASection } from "@/components/sections/cta-section"

export const metadata: Metadata = {
  title: "School Analytics Dashboard | Smart School AI",
  description: "Real-time KPI dashboards, resource optimisation, and multi-campus benchmarking. 68% reduction in admin workload.",
}

export default function AnalyticsFeaturePage() {
  return (
    <div className="bg-white">
      {/* Hero */}
      <section className="pt-24 pb-16 bg-gray-50 border-b">
        <div className="mx-auto max-w-[90rem] px-6 lg:px-8">
          <div className="max-w-3xl">
            <div className="flex items-center gap-2 text-sm font-medium text-brand-600 mb-6">
              <BarChart3 className="h-5 w-5" />
              <span>Core Administration</span>
            </div>
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl mb-6">
              Executive School Analytics
            </h1>
            <p className="text-lg text-gray-600 mb-8">
              Principals and management need a live view of operational pulse and financial health. Access predictive analytics for strategic planning and budgeting without waiting for month-end reports.
            </p>
          </div>
        </div>
      </section>

      {/* Interactive Workflow */}
      <section className="py-24">
        <div className="mx-auto max-w-[90rem] px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            
            <div className="relative">
              <Card className="bg-white shadow-2xl border-brand-100 overflow-hidden">
                <div className="bg-gray-900 px-6 py-4 flex items-center justify-between text-white">
                  <span className="font-bold">Management Dashboard</span>
                  <span className="text-xs text-brand-400">Live View</span>
                </div>
                <CardContent className="p-8 space-y-6">
                  
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-gray-50 rounded-xl border">
                      <p className="text-xs text-gray-500 mb-1">Total Enrollment</p>
                      <p className="text-lg font-bold text-gray-900 flex items-center"><TrendingUp className="h-4 w-4 me-2 text-green-500"/> Positive Trend</p>
                    </div>
                    <div className="p-4 bg-gray-50 rounded-xl border">
                      <p className="text-xs text-gray-500 mb-1">Admin Workload</p>
                      <p className="text-2xl font-bold text-gray-900">-68%</p>
                      <p className="text-xs text-brand-600 mt-1">Verified Reduction</p>
                    </div>
                  </div>

                  <div className="p-4 bg-brand-50 border border-brand-200 rounded-xl">
                    <h4 className="font-bold text-brand-900 text-sm mb-1">AI Strategic Insight</h4>
                    <p className="text-xs text-brand-700 leading-relaxed">
                      Predictive model has identified a potential cash flow variance based on historical fee collection trends. Targeted follow-ups recommended.
                    </p>
                  </div>
                  
                  <div className="text-center mt-6">
                    <span className="text-xs text-gray-400 uppercase tracking-widest font-medium">Conceptual Representation</span>
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="space-y-8">
              <h2 className="text-3xl font-bold text-gray-900">Run Your School with Intelligence</h2>
              <p className="text-lg text-gray-600">
                Data generated by the Smart School AI platform feeds directly into a centralized reporting engine, giving you an unprecedented view of your institution.
              </p>
              
              <ul className="space-y-6">
                <li className="flex gap-4 items-start">
                  <div className="h-10 w-10 rounded-full bg-brand-50 flex items-center justify-center shrink-0 mt-1 border border-brand-100">
                    <Presentation className="h-5 w-5 text-brand-600" />
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-900 text-lg">One-Click Report Generator</h4>
                    <p className="text-gray-600 text-sm mt-1">Automated reports for any school data point. Generate over 50+ compliance, audit, and governance report types instantly.</p>
                  </div>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </section>

      <CTASection />
    </div>
  )
}
